config/routes.rb
Rails.application.routes.draw do

  root 'welcome#home' 
  get 'about', to: 'welcome#about'
  
  resources 'categories'

end

app/models/category.rb
class Category < ActiveRecord::Base
    validates :name, presence: true, length: {minimum: 5, maximum: 30}
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:edit, :update, :show, :destroy]
    
    def index
        @categories = Category.all
    end
    
    def new
        @category = Category.new
    end
    
    def edit
    end
    
    def create
        # render plain:params[:category].inspect
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "Category was successfully created"
            redirect_to category_path(@category)
        else
            render 'new'
        end
    end
    
    def update
        if @category.update(category_params)
            flash[:success] = "Category was successfully updated"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end
    
    def show
    end
    
    def destroy
        @category.destroy
        flash[:danger] = "Category was successfully deleted"
        redirect_to categories_path
    end
    
    private
        def set_category
            @category = Category.find(params[:id])
        end
        def category_params
            params.require(:category).permit(:name, :description)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def home
        
    end
    
    def about
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= render "shared/errors" %>
<%= form_for(@category, :html => {class: "form-horizontal"}) do |f| %>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :name %>
        </div>
        <div class="col-sm-8">
            <%= f.text_field :name, class: "form-control", placeholder: "Name of the category"%>
        </div>
    </div>
    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :description %>
        </div>
        <div class="col-sm-8">
            <%= f.text_area :description, class: "form-control" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-8 col-sm-offset-2">
            <%= f.submit class: 'btn btn-sm btn-primary' %>
        </div>
    </div>
<% end %>

<%= link_to "Back", categories_path %>

app/views/categories/edit.html.erb
<h2>Edit existing category</h2>

<%= render 'form' %>

app/views/categories/index.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <% @categories.each do |category| %>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= category.name %>
                    </h2>
                </div>
                <div class="panel-body">
                    <p>
                    <%= truncate(category.description, length: 100) %>
                    </p>
                    <p>
                        <%= link_to "Edit", edit_category_path(category), class: "btn btn-sm btn-primary" %>
                        <%= link_to "Show", category_path(category), class: "btn btn-sm btn-success" %>
                        <%= link_to "Remove", category_path(category), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
                    </p>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/categories/new.html.erb
<h2>Create new category</h2>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title"><%= @category.name %></h2>
            </div>
            <div class="panel-body">
                <p>Description: <%= @category.description %></p>
                <hr>
                <%= link_to "Back", categories_path, class: "btn btn-sm btn-default" %>
                <%= link_to "Edit", edit_category_path, class: "btn btn-sm btn-primary" %>
                <%= link_to "Remove", category_path(@category), method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-sm btn-danger" %>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}"%>' >
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SelPo.Mw", root_path, class: "navbar-brand", id: "logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><%= link_to "Categories", categories_path %></li>
        <li><a href="#">Products</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New category", new_category_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>
  <hr>
  <footer>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-1">
         Copyright &copy; <a href="http://www.statechconsultant.weebly.com">Statech Malawi</a>
      </div>
    </div>
  </footer>
  

app/views/shared/_errors.html.erb
<% if @category.errors.any? %>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h2 class="panel-title">
                    <%= pluralize(@category.errors.count, "error") %>
                    prohibited this category from being creted
                </h2>
                <ul>
                    <% @category.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/welcome/about.html.erb
<h2>This is an about page</h2>

<%= link_to "Home", root_path %>

app/views/welcome/home.html.erb
<div class="jumbotron">
    
</div>

<%= link_to "Categories", categories_path %> | <%= link_to "About", about_path %>